package rss;

import java.sql.ResultSet;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;

/**
 * This is the AddCaseNotes class. It adds a new set of case notes to a case in the database.
 * 
 * @author Spaced
 */
public class AddCaseNotes extends javax.swing.JFrame {

    /**
     * Creates new form AddCaseNotes
     */
    public AddCaseNotes() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookedloadbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        casetbl = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        notearea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookedTbl1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        caseidfld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookedloadbtn.setText("Main Menue");
        bookedloadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookedloadbtnActionPerformed(evt);
            }
        });

        casetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        casetbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casetblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(casetbl);

        notearea.setColumns(20);
        notearea.setRows(5);
        jScrollPane1.setViewportView(notearea);

        bookedTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookedTbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookedTbl1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bookedTbl1);

        jButton1.setText("Save Notes of the Case");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        caseidfld.setText("Select an appointment from the table to add notes");

        jLabel1.setText("Case Id to add notes to ");

        jLabel2.setText("Write Case notes Below");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addComponent(bookedloadbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(caseidfld, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookedloadbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseidfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is the back method. It allows the user to return to the main menu.
     * 
     * @param evt the action event
     */
    private void bookedloadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookedloadbtnActionPerformed
        MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
    }//GEN-LAST:event_bookedloadbtnActionPerformed

    /**
     * This is the select case method. It allows the user to select an entry in the case table and edit it.
     * 
     * @param evt the mouse event
     */
    private void casetblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casetblMouseClicked

        rssDatabase rss= new rssDatabase();
        int row = bookedTbl1.getSelectedRow();
        int caseid = Integer.parseInt(bookedTbl1.getModel().getValueAt(row,6).toString());
        
        ResultSet rsst = rss.findcase(caseid);
        casetbl.setModel(DbUtils.resultSetToTableModel(rsst));
        
        
    }//GEN-LAST:event_casetblMouseClicked

    /**
     * This is the select booked case method. It allows the user to select a booked case in the case table and edit it.
     * 
     * @param evt the mouse event
     */
    private void bookedTbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookedTbl1MouseClicked

        rssDatabase rss= new rssDatabase();
        int row = bookedTbl1.getSelectedRow();
        int caseid = Integer.parseInt(bookedTbl1.getModel().getValueAt(row,6).toString());
       
        caseidfld.setText(Integer.toBinaryString(caseid));
        ResultSet rsst = rss.findcase(caseid);
        casetbl.setModel(DbUtils.resultSetToTableModel(rsst));
    }//GEN-LAST:event_bookedTbl1MouseClicked

    /**
     * This is the add case notes method. It adds a new set of case notes to the database.
     * 
     * @param evt the action event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Case cs = new Case();
        cs.setCaseid(Integer.parseInt(caseidfld.getText()));
        cs.setCaseNotes(notearea.getText());
        rssDatabase rss= new rssDatabase();
        rss.updatecase(cs);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable bookedTbl1;
    private javax.swing.JButton bookedloadbtn;
    private javax.swing.JTextField caseidfld;
    private javax.swing.JTable casetbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea notearea;
    // End of variables declaration//GEN-END:variables
}
