package rss;


import javax.swing.JFrame;


/**
 * This is the addcaseworker class. It allows the user to add a new caseworker to the database.
 * 
 * @author Spaced
 */
public class addcaseworker extends javax.swing.JFrame {

    /**
     * Creates new form testresultset
     */
    String a="";
    public addcaseworker() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnamefld = new javax.swing.JTextField();
        lastnamefld = new javax.swing.JTextField();
        emailfld = new javax.swing.JTextField();
        contactfld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        housingcbx = new javax.swing.JCheckBox();
        employmentcbx = new javax.swing.JCheckBox();
        debtcbx = new javax.swing.JCheckBox();
        benifitcbx = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstnamefld.setText("Enter First Name here");
        firstnamefld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefldMouseClicked(evt);
            }
        });
        firstnamefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefldActionPerformed(evt);
            }
        });

        lastnamefld.setText("Enter Last Name here");
        lastnamefld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastnamefldMouseClicked(evt);
            }
        });

        emailfld.setText("Enter Email here");
        emailfld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailfldMouseClicked(evt);
            }
        });
        emailfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfldActionPerformed(evt);
            }
        });

        contactfld.setText("Enter Contact Number here");
        contactfld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactfldMouseClicked(evt);
            }
        });
        contactfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfldActionPerformed(evt);
            }
        });

        jButton1.setText("Add Case Worker");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("FirstName");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Contact");

        jLabel6.setText("Category");

        jLabel7.setText("Add a New CaseWorker");

        housingcbx.setText("housing");
        housingcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingcbxActionPerformed(evt);
            }
        });

        employmentcbx.setText("employment");
        employmentcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employmentcbxActionPerformed(evt);
            }
        });

        debtcbx.setText("debt");
        debtcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtcbxActionPerformed(evt);
            }
        });

        benifitcbx.setText("benifit");
        benifitcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benifitcbxActionPerformed(evt);
            }
        });

        backBtn.setText("Main Menue");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(employmentcbx)
                                    .addGap(9, 9, 9)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lastnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailfld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactfld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(housingcbx)
                                    .addGap(18, 18, 18)
                                    .addComponent(debtcbx)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(benifitcbx)))
                .addContainerGap(515, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emailfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(contactfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingcbx)
                    .addComponent(debtcbx)
                    .addComponent(benifitcbx)
                    .addComponent(employmentcbx))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void emailfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfldActionPerformed

    }//GEN-LAST:event_emailfldActionPerformed

    private void contactfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfldActionPerformed

    }//GEN-LAST:event_contactfldActionPerformed

    /**
     * This is the add caseworker method. It adds a new caseworker to the database.
     * 
     * @param evt the action event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        
            CaseWorker csw=new CaseWorker();
            rssDatabase rssdb = new rssDatabase();
            
                    csw.setFirstName(firstnamefld.getText());
                    csw.setLastName(lastnamefld.getText());
                    csw.setEmail(emailfld.getText());
                    int contact = Integer.parseInt(contactfld.getText());
                    csw.setContact(contact);
                    
                    csw.setCategory(a);
                  
                    rssdb.addcasworker(csw);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnamefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefldActionPerformed

    }//GEN-LAST:event_firstnamefldActionPerformed

    /**
     * This is the select contact field method. It sets the initial field to be blank.
     * 
     * @param evt the mouse event
     */
    private void contactfldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactfldMouseClicked

        contactfld.setText("");
    }//GEN-LAST:event_contactfldMouseClicked

    /**
     * This is the select email field method. It sets the initial field to be blank.
     * 
     * @param evt the mouse event
     */
    private void emailfldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailfldMouseClicked

        emailfld.setText("");
    }//GEN-LAST:event_emailfldMouseClicked

    /**
     * This is the select last name field method. It sets the initial field to be blank.
     * 
     * @param evt the mouse event
     */
    private void lastnamefldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastnamefldMouseClicked
        
        lastnamefld.setText("");
    }//GEN-LAST:event_lastnamefldMouseClicked

    /**
     * This is the select first name field method. It sets the initial field to be blank.
     * 
     * @param evt the mouse event
     */
    private void firstnamefldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefldMouseClicked
        // TODO add your handling code here:
        firstnamefld.setText("");
    }//GEN-LAST:event_firstnamefldMouseClicked

    /**
     * This is the select combobox employment method. It lets the user select the case category that the caseworker is proficient in.
     * 
     * @param evt the action event
     */
    private void employmentcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employmentcbxActionPerformed

       if(employmentcbx.isSelected()){
        a=a+employmentcbx.getText();
        System.out.println("1"+a);}
       else{
       a=a.replaceAll("employment","" );
           System.out.println(a);}
    }//GEN-LAST:event_employmentcbxActionPerformed

    /**
     * This is the select combobox housing method. It lets the user select the case category that the caseworker is proficient in.
     * 
     * @param evt the action event
     */
    private void housingcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingcbxActionPerformed

       if(housingcbx.isSelected()){a=a+housingcbx.getText();
        System.out.println("2"+a);}
       else{
           a=a.replaceAll("housing","" );
           System.out.println(a);
       }
    }//GEN-LAST:event_housingcbxActionPerformed

    /**
     * This is the select combobox debt method. It lets the user select the case category that the caseworker is proficient in.
     * 
     * @param evt the action event
     */
    private void debtcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtcbxActionPerformed
        // TODO add your handling code here:
       if(debtcbx.isSelected()){ a=a+debtcbx.getText();
        System.out.println("3"+a);}else{a=a.replaceAll("debt","" );
           System.out.println(a);}
        
    }//GEN-LAST:event_debtcbxActionPerformed

    /**
     * This is the select combobox benefit method. It lets the user select the case category that the caseworker is proficient in.
     * 
     * @param evt the action event
     */
    private void benifitcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benifitcbxActionPerformed
        // TODO add your handling code here:
        if(benifitcbx.isSelected()){a=a+benifitcbx.getText();
        System.out.println("4"+a);}else{a=a.replaceAll("benifit","" );
           System.out.println(a);}
    }//GEN-LAST:event_benifitcbxActionPerformed

    /**
     * This is the back method. It returns the user to the main menu.
     * 
     * @param evt the action event
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JCheckBox benifitcbx;
    private javax.swing.JTextField contactfld;
    private javax.swing.JCheckBox debtcbx;
    private javax.swing.JTextField emailfld;
    private javax.swing.JCheckBox employmentcbx;
    private javax.swing.JTextField firstnamefld;
    private javax.swing.JCheckBox housingcbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastnamefld;
    // End of variables declaration//GEN-END:variables
}
