package rss;

import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 * This is the AddCase class. It adds an appointment to the database
 * 
 * @author Spaced
 */
public class AddCase extends javax.swing.JFrame {

    /**
     * Creates new form AddCase
     */
    public AddCase() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientTbl = new javax.swing.JTable();
        addcasebtn = new javax.swing.JButton();
        clientidfld = new javax.swing.JTextField();
        casestartdatefld = new javax.swing.JTextField();
        casefirstmeetingfld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loadclientbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        catlist = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        casenotestxt = new javax.swing.JTextArea();
        addcasebtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTbl);

        addcasebtn.setText("Add Case");
        addcasebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcasebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Client ID");

        jLabel3.setText("Case Category");

        jLabel4.setText("Case Start Date");

        jLabel6.setText("Case Note");

        jLabel7.setText("First Meeting");

        loadclientbtn.setText("Load Clients");
        loadclientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadclientbtnActionPerformed(evt);
            }
        });

        catlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "debt", "housing", "employment","benefit"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(catlist);

        casenotestxt.setColumns(20);
        casenotestxt.setRows(5);
        jScrollPane3.setViewportView(casenotestxt);

        addcasebtn1.setText("Main Menue");
        addcasebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcasebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadclientbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addcasebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(casestartdatefld, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(clientidfld, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(casefirstmeetingfld, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 338, Short.MAX_VALUE))
                    .addComponent(addcasebtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadclientbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clientidfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casestartdatefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(casefirstmeetingfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addcasebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addcasebtn1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * This is the client load method. It loads a list of clients directly from the database.
     * 
     * @param evt the action event
     */
    private void loadclientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadclientbtnActionPerformed
        rssDatabase rsj= new rssDatabase();
        ResultSet rs =rsj.loadclients();
        clientTbl.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_loadclientbtnActionPerformed

    /**
     * This is the add case method. It adds a new case directly to the database.
     * 
     * @param evt the action event
     */
    private void addcasebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcasebtnActionPerformed
        Case newcase= new Case();
        if(clientidfld.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "select a client from the table ");}else{
        int clientid=Integer.parseInt(clientidfld.getText());
        newcase.setClientid(clientid);
        newcase.setCaseStartDate(casestartdatefld.getText());
        newcase.setCasecategory(catlist.getSelectedValue().toString());
        newcase.setCaseNotes(casenotestxt.getText());
        rssDatabase rssdb= new rssDatabase();
        
        rssdb.addcase(newcase);}
    }//GEN-LAST:event_addcasebtnActionPerformed

    /**
     * This is the select client method. It allows the user to select an entry in the client table and edit it.
     * 
     * @param evt the mouse event
     */
    private void clientTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTblMouseClicked
      Integer row= clientTbl.getSelectedRow();
       clientidfld.setText(clientTbl.getModel().getValueAt(row, 0).toString());
       java.util.Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");  
        String strDate = dateFormat.format(date);
        casestartdatefld.setText(strDate);
        casefirstmeetingfld.setText("null");
        casefirstmeetingfld.setEditable(false);
        casestartdatefld.setEditable(false);
       clientidfld.setEditable(false);
    }//GEN-LAST:event_clientTblMouseClicked

    /**
     * This is the back method. It allows the user to return back to the main menu.
     * 
     * @param evt the action event
     */
    private void addcasebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcasebtn1ActionPerformed
        
        MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
        
        
        
       
    }//GEN-LAST:event_addcasebtn1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcasebtn;
    private javax.swing.JButton addcasebtn1;
    private javax.swing.JTextField casefirstmeetingfld;
    private javax.swing.JTextArea casenotestxt;
    private javax.swing.JTextField casestartdatefld;
    private javax.swing.JList catlist;
    public javax.swing.JTable clientTbl;
    private javax.swing.JTextField clientidfld;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadclientbtn;
    // End of variables declaration//GEN-END:variables
}
