package rss;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 * This is the addCaseWorkerAvailibility class. It allows the user to assign a case worker to a time slot to mark them as available.
 * 
 * @author Spaced
 */
public class addCaseWorkerAvailibilty extends javax.swing.JFrame {

    /**
     * Creates new form addCaseWorkerAvailibilty
     */
    public addCaseWorkerAvailibilty() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tstbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cwtbl = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cwidfld = new javax.swing.JTextField();
        tsidfld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cwloadbtn = new javax.swing.JButton();
        tsloadbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        apptbl = new javax.swing.JTable();
        loadappbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tstbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 57, 601, 182));

        cwtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cwtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cwtblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cwtbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 494, 182));

        addbtn.setText("Add availaibilty");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 427, 141, -1));

        jLabel1.setText("Case Worker ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 343, 124, -1));

        jLabel2.setText("Time SLot ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 392, -1, -1));
        getContentPane().add(cwidfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 340, 285, -1));
        getContentPane().add(tsidfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 389, 285, -1));

        jLabel3.setText("To add new availaibilty add a caseworker and timeslot id in the fields below");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 308, 308, -1));

        cwloadbtn.setText("load Case Worker");
        cwloadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwloadbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cwloadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 267, 494, -1));

        tsloadbtn.setText("load time slots");
        tsloadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsloadbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tsloadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 245, 354, -1));

        apptbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        apptbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(apptbl);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 286, 601, 182));

        loadappbtn.setText("load available appoitnments");
        loadappbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadappbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loadappbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 474, -1, -1));

        jLabel4.setText("available case workers ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 25, 124, -1));

        jLabel5.setText("available time slots");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 37, 124, -1));

        backBtn.setText("Main Menue");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is the show caseworkers method. It displays the list of caseworkers from the database in a table.
     * 
     * @param evt the action event
     */
    private void cwloadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwloadbtnActionPerformed
            rssDatabase rsj= new rssDatabase();
        ResultSet rs =rsj.loadcwdetails();
        cwtbl.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_cwloadbtnActionPerformed

    /**
     * This is the show time slots method. It displays the list of available time slots from the database in a table.
     * 
     * @param evt the action event
     */
    private void tsloadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsloadbtnActionPerformed
     rssDatabase rsj= new rssDatabase();
     ResultSet rs=rsj.loadTimeSlots();
     tstbl.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_tsloadbtnActionPerformed

    /**
     * This is the select caseworker method. It allows the user to select an entry from the caseworker table.
     * 
     * @param evt the mouse event
     */
    private void cwtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cwtblMouseClicked
        int i=cwtbl.getSelectedRow();
        TableModel model=cwtbl.getModel();
        cwidfld.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_cwtblMouseClicked

    /**
     * This is the select time slot method. It allows the user to select an entry from the time slot table.
     * 
     * @param evt the mouse event
     */
    private void tstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tstblMouseClicked
        int i=tstbl.getSelectedRow();
        TableModel model=tstbl.getModel();
        tsidfld.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tstblMouseClicked

    /**
     * This is the add appointment method. It allows the user to add a new appointment that matches the case worker's preferred time slot.
     * 
     * @param evt the action event
     */
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       Appointment ap= new Appointment();
       Integer i=null;
       Integer cwid=Integer.parseInt(cwidfld.getText());
       ap.setCwID(cwid);
       Integer tsid= Integer.parseInt(tsidfld.getText());
       ap.setTimeSlotID(tsid);
       rssDatabase rs= new rssDatabase();
       rs.insertap(ap);
       
       
    }//GEN-LAST:event_addbtnActionPerformed

    private void apptblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptblMouseClicked
       
    }//GEN-LAST:event_apptblMouseClicked

    /**
     * This is the load appointments method. It loads a list of available appointments from the database.
     * 
     * @param evt the action event
     */
    private void loadappbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadappbtnActionPerformed
         rssDatabase rsj= new rssDatabase();
        ResultSet rs2 =rsj.loadavailableappointment();
        apptbl.setModel(DbUtils.resultSetToTableModel(rs2));
    }//GEN-LAST:event_loadappbtnActionPerformed

    /**
     * This is the back method. It returns the user to the main menu.
     * 
     * @param evt the action event
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTable apptbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cwidfld;
    private javax.swing.JButton cwloadbtn;
    private javax.swing.JTable cwtbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadappbtn;
    private javax.swing.JTextField tsidfld;
    private javax.swing.JButton tsloadbtn;
    private javax.swing.JTable tstbl;
    // End of variables declaration//GEN-END:variables
}
