package rss;



import java.text.SimpleDateFormat;
import javax.swing.JFrame;


/**
 * This is the addTimeSlot class. It allows the user to add a new time slot to the database.
 * 
 * @author Spaced
 */
public class addTimeSlot extends javax.swing.JFrame {

    /**
     * Creates new form addTimeSlot
     */
    public addTimeSlot() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        addtmslotbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timecobx = new javax.swing.JComboBox();
        roomncobx = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));

        addtmslotbtn.setText("Add Time Slot");
        addtmslotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtmslotbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addtmslotbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel2.setText("Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, -1));

        jLabel3.setText("Room Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        timecobx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10:00", "11:00", "12:00", "13:00" }));
        timecobx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timecobxActionPerformed(evt);
            }
        });
        getContentPane().add(timecobx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, -1));

        roomncobx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1","2","3" }));
        getContentPane().add(roomncobx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        jLabel4.setText("Add a Time Slot");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 300, 260));

        backBtn.setText("Main Menue");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is the add time slot method. It adds a new time slot to the database.
     * 
     * @param evt the action event
     */
    private void addtmslotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtmslotbtnActionPerformed
        TimeSlot tm = new TimeSlot();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String date = sdf.format(jDateChooser1.getDate());
        tm.setDate(date);
        tm.setTime(date);
        String time=(String)timecobx.getSelectedItem();
        tm.setTime(time);
        String roomnumber=(String)roomncobx.getSelectedItem();
        tm.setRoomNumber(roomnumber);
        rssDatabase rs= new rssDatabase();
        rs.addtimeslot(tm); 
    }//GEN-LAST:event_addtmslotbtnActionPerformed

    private void timecobxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timecobxActionPerformed

    }//GEN-LAST:event_timecobxActionPerformed

    /**
     * This is the back method. It returns the user to the main menu.
     * 
     * @param evt the action event
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtmslotbtn;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox roomncobx;
    private javax.swing.JComboBox timecobx;
    // End of variables declaration//GEN-END:variables
}
