package rss;

import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 * This is the CloseCase class. It allows the user to close a case.
 * 
 * @author Spaced
 */
public class CloseCase extends javax.swing.JFrame {

    /**
     * Creates new form CloseCase
     */
    public CloseCase() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookedloadbtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookedTbl1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        caseidfld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notearea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        casetbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookedloadbtn.setText("Main Menue");
        bookedloadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookedloadbtnActionPerformed(evt);
            }
        });

        bookedTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookedTbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookedTbl1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bookedTbl1);

        jLabel1.setText("Case Id to add notes to ");

        caseidfld.setText("Select an appointment from the table to add To Close the Case");

        jButton1.setText("Close the case");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        notearea.setColumns(20);
        notearea.setRows(5);
        jScrollPane1.setViewportView(notearea);

        jLabel2.setText("Write Case Closing Notes Below");

        casetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        casetbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casetblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(casetbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookedloadbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(caseidfld, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookedloadbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caseidfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is the back method. It allows the user to return to the main menu.
     * 
     * @param evt the action event
     */
    private void bookedloadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookedloadbtnActionPerformed
         MainMenue M = new MainMenue();
        this.dispose();
        M.setVisible(true);
    }//GEN-LAST:event_bookedloadbtnActionPerformed

    /**
     * This is the select case method. It allows the user to select an entry from the case table for deletion.
     * 
     * @param evt the mouse event
     */
    private void bookedTbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookedTbl1MouseClicked
        // TODO add your handling code here:
        rssDatabase rss= new rssDatabase();
        int row = bookedTbl1.getSelectedRow();
        int caseid = Integer.parseInt(bookedTbl1.getModel().getValueAt(row,6).toString());

        caseidfld.setText(Integer.toString(caseid));
        ResultSet rsst = rss.findcase(caseid);
        casetbl.setModel(DbUtils.resultSetToTableModel(rsst));
        
    }//GEN-LAST:event_bookedTbl1MouseClicked
   
    /**
     * This is the date method. It returns the current date.
     * 
     * @return the date
     */
    public String date(){
        java.util.Date date = Calendar.getInstance().getTime();  
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");  
String strDate = dateFormat.format(date); 
        System.out.println(strDate);
    return strDate;
    }
    
    /**
     * This is the close case method. It closes the selected case.
     * 
     * @param evt the action event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Case cs = new Case();
        cs.setCaseid(Integer.parseInt(caseidfld.getText()));
        cs.setClosingNotes(notearea.getText());
        cs.setCaseCloseDate(date());
        System.out.println(cs.getCaseCloseDate());
        rssDatabase rss= new rssDatabase();
        rss.closecase(cs);
        JOptionPane.showMessageDialog(null, "case Number ( " + cs.getCaseid() + ") has been closed");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * This is the case table method. It works together with the select case method to allow the user to select cases that they want to close.
     * 
     * @param evt the mouse event
     */
    private void casetblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casetblMouseClicked

        rssDatabase rss= new rssDatabase();
        int row = bookedTbl1.getSelectedRow();
        int caseid = Integer.parseInt(bookedTbl1.getModel().getValueAt(row,6).toString());

        ResultSet rsst = rss.findcase(caseid);
        casetbl.setModel(DbUtils.resultSetToTableModel(rsst));

    }//GEN-LAST:event_casetblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable bookedTbl1;
    private javax.swing.JButton bookedloadbtn;
    private javax.swing.JTextField caseidfld;
    private javax.swing.JTable casetbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea notearea;
    // End of variables declaration//GEN-END:variables
}
